### ISSUE TITLE
启动不起来，提示初始化客户端失败

### ISSUE THREAD

**Issue by liangshengmoran** [krau/SaveAny-Bot#1]
![image](https://github.com/user-attachments/assets/50c565df-6e26-44da-9629-1b0577aa281f)
启动不起来，提示初始化客户端失败

配置文件：
![Snipaste_2024-12-02_12-45-47](https://github.com/user-attachments/assets/4d30f28e-562f-4f9d-afbf-fb743625461d)

**Comment by krau** [comment]
把 `api_id` 和 `api_hash` 改成 `app_id` 和 `app_hash` , 示例配置写错了, 感谢反馈

**Comment by liangshengmoran** [comment]
已解决
